local M = {}

local group = 'debug_autocmd'
local events = {
  'BufAdd',
  'BufDelete',
  'BufEnter',
  'BufFilePost',
  'BufFilePre',
  -- 'BufHidden',
  'BufLeave',
  'BufModifiedSet',
  -- 'BufNew',
  'BufNewFile',
  -- 'BufRead',
  'BufReadPost',
  -- 'BufReadCmd',
  -- 'BufReadPre',
  -- 'BufUnload',
  'BufWinEnter',
  -- 'BufWinLeave',
  -- 'BufWipeout',
  -- 'BufWrite',
  -- 'BufWritePre',
  -- 'BufWriteCmd',
  'BufWritePost',
  'ChanInfo',
  -- 'ChanOpen',
  'CmdUndefined',
  -- 'CmdlineChanged',
  -- 'CmdlineEnter',
  -- 'CmdlineLeave',
  -- 'CmdwinEnter',
  -- 'CmdwinLeave',
  'ColorScheme',
  'ColorSchemePre',
  -- 'CompleteChanged',
  -- 'CompleteDonePre',
  -- 'CompleteDone',
  -- 'CursorHold',
  -- 'CursorHoldI',
  -- 'CursorMoved',
  -- 'CursorMovedI',
  'DiffUpdated',
  'DirChanged',
  -- 'DirChangedPre',
  'ExitPre',
  -- 'FileAppendCmd',
  -- 'FileAppendPost',
  -- 'FileAppendPre',
  -- 'FileChangedRO',
  -- 'FileChangedShell',
  -- 'FileChangedShellPost',
  -- 'FileReadCmd',
  -- 'FileReadPost',
  -- 'FileReadPre',
  -- 'FileType',
  -- 'FileWriteCmd',
  -- 'FileWritePost',
  -- 'FileWritePre',
  -- 'FilterReadPost',
  -- 'FilterReadPre',
  -- 'FilterWritePost',
  -- 'FilterWritePre',
  'FocusGained',
  'FocusLost',
  -- 'FuncUndefined',
  'UIEnter',
  'UILeave',
  -- 'InsertChange',
  -- 'InsertCharPre',
  'InsertEnter',
  -- 'InsertLeavePre',
  'InsertLeave',
  -- 'MenuPopup',
  -- 'ModeChanged',
  -- 'OptionSet',
  -- 'QuickFixCmdPre',
  -- 'QuickFixCmdPost',
  'QuitPre',
  'RemoteReply',
  'SearchWrapped',
  'RecordingEnter',
  'RecordingLeave',
  'SessionLoadPost',
  -- 'ShellCmdPost',
  'Signal',
  -- 'ShellFilterPost',
  -- 'SourcePre', テキストロック
  -- 'SourcePost', テキストロック
  -- 'SourceCmd',
  -- 'SpellFileMissing',
  -- 'StdinReadPost',
  -- 'StdinReadPre',
  -- 'SwapExists',
  -- 'Syntax',
  -- 'TabEnter',
  -- 'TabLeave',
  -- 'TabNew',
  -- 'TabNewEntered',
  -- 'TabClosed',
  -- 'TermOpen',
  -- 'TermEnter',
  -- 'TermLeave',
  -- 'TermClose',
  -- 'TermResponse',
  -- 'TextChanged',
  -- 'TextChangedI',
  -- 'TextChangedP',
  -- 'TextChangedT',
  -- 'TextYankPost',
  -- 'User',
  -- 'UserGettingBored',
  'VimEnter',
  'VimLeave',
  'VimLeavePre',
  'VimResized',
  'VimResume',
  'VimSuspend',
  -- 'WinClosed', 無限ループ
  'WinEnter',
  'WinLeave',
  'WinNew',
  -- 'WinScrolled',
  -- 'WinResized',
}

M.on = function ()
  vim.api.nvim_create_augroup (group, {clear = true})
  vim.api.nvim_create_autocmd (events, { group = group, callback = function (a)
    vim.notify (string.format ("%s\n\n<amatch> = %s\n<afile>  = %s\ndata = %s", a.event, a.match, a.file, vim.inspect (a.data)))
  end })
end

M.off = function ()
  vim.api.nvim_clear_autocmds ({group = group})
end

return M

