abbrev-alias -c :q=exit
abbrev-alias -c e=nvim
abbrev-alias -c g=git
abbrev-alias -c la='ls -A'
abbrev-alias -c ll='ls -lA'
abbrev-alias -c cp='cp -i'
abbrev-alias -c mv='mv -i'
abbrev-alias -c rm='rm -i'
abbrev-alias -c rr='rm -ri'
abbrev-alias -c ln='ln -snfv'
abbrev-alias -c type='type -as'
# abbrev-alias -c history='history 0'
abbrev-alias -c historygrep='history | grep'
abbrev-alias -c vscode=code
abbrev-alias -c gitconfig='git config --global -e'
abbrev-alias -c pacman='sudo pacman'
abbrev-alias -c push='git push'
abbrev-alias -cr pushu='push -u origin HEAD'
abbrev-alias -c gs='git status'
abbrev-alias -c firstcommit='git commit -m "First commit."'
