[colors]
draw_bold_text_with_bright_colors = true

# Colors (Tomorrow Night Bright)
# Default colors
[colors.primary]
#foreground = '#eaeaea'
#background = '#111111'
foreground = '#c5c8c6'
background = '#1d1f21'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#d54e53'
green   = '#b9ca4a'
yellow  = '#e6c547'
blue    = '#7aa6da'
magenta = '#c397d8'
cyan    = '#70c0ba'
#white   = '#424242'
white   = '#c5c8c6'

# Bright colors
[colors.bright]
black   = '#666666'
red     = '#ff3334'
green   = '#9ec400'
yellow  = '#e7c547'
blue    = '#7aa6da'
magenta = '#b77ee0'
cyan    = '#54ced6'
white   = '#eaeaea'

[font]
size = 12

[font.bold]
family = "alacritty-monospace"
style = "Bold"

[font.bold_italic]
family = "alacritty-monospace"
style = "Bold Italic"

[font.italic]
family = "alacritty-monospace"
style = "Medium"

[font.normal]
family = "alacritty-monospace"
style = "Medium"

[[keyboard.bindings]]
chars = "\u0017"
key = "Back"
mods = "Control"

# [[keyboard.bindings]]
# chars = "\u001F"
# key = "Slash"
# mods = "Control"

# [window]
# opacity = 0.8
